### PR TITLE
removes the 'shimmy' service

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
merge if happy

**Comment by lsh-0** [comment]
it wont. if it's running it will continue to run. if it stops it won't be started again.

I guess for processes that *are* running and need to be removed, first reduce their number to 0 *then* remove them...

**Comment by thewilkybarkid** [comment]
Forgot about that name!

**Comment by lsh-0** [comment]
how earth did you come across this ticket so quickly, @thewilkybarkid ? you're not subscribed... Was it the slack thing?

**Comment by thewilkybarkid** [comment]
Watching the repo so I get notifications. Just happening to be going through them.

**Pull request merged**
