### PR TITLE
Config file letterparser.cfg

### PR DESCRIPTION
**Pull request by gnott**
Related to issue https://github.com/elifesciences/decision-letter-parser/issues/43

I created a config file named `letterparser.cfg` that will be used by the decision letter parser library in an `elife-bot` workflow in the future. I'm adding the file to this formula now before I forget.

- [x] Update `letterparser.cfg` to latest before merging

### CODE REVIEW

**Comment by gnott** [comment]
It is my understanding based on the previous patterns of including `.cfg` files into the elife-bot instance that the file should go into this project. The `letterparser.cfg` (and the other `.cfg` files from other libraries) are no part of the python module's distribution package. Another way I could see adding this would be to commit it directly to the root folder of the `elife-bot` project. As I say, I thought this was the method to populate or overwrite files on an EC2 instance.

Regarding the Docker usage, I incorporated this into the `letterparser` library as a fallback option for invoking `pandoc`, which is not available on the instance. I am not aware of how you'd like to manage docker images, so I would need help or someone to take it to the finish line.

**Comment by giorgiosironi** [comment]
> The letterparser.cfg (and the other .cfg files from other libraries) are no part of the python module's distribution package. Another way I could see adding this would be to commit it directly to the root folder of the elife-bot project.

You're right that a configuration file should not be part of the distributable package of the library. But it's also unexpected that a library depends on reading a particular file from the current working directory, as incuding the Python modules from there results in additional I/O.

**Comment by gnott** [comment]
I'm not sure I understand which are the topics of discussion here clearly enough. If how the `.cfg` files are used is in question, and there is a better alternative, please do suggest it. I guess the central example config file is https://github.com/elifesciences/elife-crossref-xml-generation/blob/develop/crossref.cfg  which was a way to not hard-code `https://elifesciences.org` throughout the library code.

**Comment by gnott** [comment]
I should also clarify the `.cfg` file does not necessarily have to be included in the `"current working directory"`. In the `elife-bot` project, we specify the path to the `.cfg` file. The test scenarios use a different `.cfg` file, which is stored in the `tests/` folder. The `.cfg` files can be located anywhere on the system.

**Comment by lsh-0** [comment]
so .. `elife-bot` is incorporating a library called `letterparser` ([this one?](https://github.com/elifesciences/decision-letter-parser)).

`letterparser` depends on reading values from a configuration file. 

The default values of this configuration file [are here](https://github.com/elifesciences/elife-crossref-xml-generation/blob/develop/crossref.cfg).

Will the values in the config file in this PR will be used to override the values in the above file? Because there are properties present that aren't in there, like `ELIFE.docker_image` and `ELIFE.preamble`.

Or does this file contain additional configuration properties unrelated to the above linked config file? If so, why aren't they part of the typical `elife-bot` [settings.py](https://github.com/elifesciences/elife-bot/blob/develop/settings-example.py) file and in this separate file?

**Comment by gnott** [comment]
I made some assumptions that this PR would follow the same convention of all the other `.cfg` files the `elife-bot` project is using, and this PR is also only partially complete, since no mention of the `letterparser.cfg` file is in the bot `settings.py` file yet, and by following the previous convention I didn't need to provide lots of detail about why I am adding this file.

The `elife-bot` project will eventually use `letterparser` - correct! I haven't built that yet. This week I filled out the issue describing the workflow I'm planning to build on https://github.com/elifesciences/elife-bot/issues/965

The config file from the `elife-crossref-xml-generation` project will not be used by `letterparser`. The link I provided to the Crossref one was to illustrate how these config files specify the elife-specific strings, patterns, and flags used by a similar code library.

The `[DEFAULT]` section is mentioned a bit in https://docs.python.org/3/library/configparser.html, and either the default values get included automatically, or the config file reading logic I added uses the default values if no value is specified in the specific config section. I cannot remember exactly, but it seems to be working properly. The `[elife]` section we could be explicit to specify values if we want to.

Since these separate code libraries do not have a `settings.py` file, and instead use the `configparser` and ` .cfg` file, that's why I am loading them from the `.cfg` file. The config is not dependent on the `elife-bot` project, except to specify the path to the `.cfg` file to be loaded.

There is a `.cfg` file in the `bot-lax-adaptor` and it uses `configparser`, which caused me to think it is not totally foreign to have these files.

Thanks for the questions, I was a little confused (and am still a little confused) if there are some material deficiencies with what I'm trying to do here, and in which project or step is what we are addressing.

**Comment by lsh-0** [comment]
thanks for the reply, @gnott . I think sometimes a proposed change manages to hook our attention and then we pick it to death during review because we have the opportunity to assert how the world *should* look to others, while very similar changes manage to avoid our attention and make it through without contest. 

elife-bot is a large sprawling codebase and my concern is that it's aggregating a new collection of config files in addition to the already very large `settings.py`.

I'm ok with the change going through because I largely trust you and other developers to do the right thing and because it's rarely me doing the debugging on elife-bot. At the sysadmin level when the elife-bot instances need updating then I'd prefer the developer not have to deal with the formula, or if they must, keep the changes to as few as possible - hence my preference for a single gigantic settings.py file over settings.py + multiple `.cfg` files.

From the sounds of it there are other similar files already required and approval of this PR is blocking other work from happening.

I'll approve this PR but I'm not keen on the pattern that is emerging.

**Comment by gnott** [comment]
Thanks @lsh-0! I've since added some values and I'll update the file here when I feel like the config has all the final values. We won't need this file until the workflow development is further along, probably a week or more for me.

**Comment by gnott** [comment]
I've updated `letterparser.cfg` to have the latest values I'm using, now that parsing is further along. The docker image name is changed, and there are a couple more config options used in generating file names.

**Pull request merged**
