### PR TITLE
Add assessment_terms.yaml file

### PR DESCRIPTION
**Pull request by gnott**
Re issue https://github.com/elifesciences/issues/issues/8176

Adding another YAML file to the instance. Only if you have time to take a peek at the salt portion @lsh-0, no worries if not.

### CODE REVIEW

**Comment by lsh-0** [comment]
I'll take a look now :)

**Comment by lsh-0** [comment]
huh - failed to create a stack. I wonder if this has anything to do with too-long names again. I'll investigate this now.

**Comment by gnott** [comment]
Thanks, I'll refrain from creating a separate issue about the build pipeline, no rush really but if you can this week it'd be cool.

**Comment by lsh-0** [comment]
> huh - failed to create a stack. I wonder if this has anything to do with too-long names again. I'll investigate this now.

Doesn't seem like it (thank goodness):

Screenshot at 2023-04-13 11-10-57

and

Screenshot at 2023-04-13 11-11-26

and I don't see `Pr107BaseUpdateElifePublishedBucket` mentioned any where in the other stack that was being created ... could just be a rare once-off thing. I'll give the build a kick and see what happens.

**Review by lsh-0 — APPROVED** [review]
seems fine

build failure seems unrelated

**Comment by gnott** [comment]
Cool, thanks again @lsh-0 !

**Pull request merged**
