### PR TITLE
18.04 upgrade

### PR DESCRIPTION
**Pull request by lsh-0**
* adds a standalone 18.04 build

- [x] blocked by: https://github.com/elifesciences/builder/pull/652

### CODE REVIEW

**Comment by lsh-0** [comment]
stack creation failed
```
[2020-04-16T03:16:08.739Z]   'You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: 257EDB1B0FCF558D; S3 Extended Request ID: 96NGzlFOFYEUEzBlLoCFxYy4s/0pq4OAY6XKjRyBWwMG9i09WiA1I/OSzy11MD86JzxycdFhH8M=)'),
```

**Comment by giorgiosironi** [comment]
Two things:
1. Can you check we aren't leaving around buckets from this builds? Anything with `pr-` somewhere in the name is suspicious.
2. The alternate configurations used in this build (`standalone` but also `s1804`, `snsalt`) should be configured to not create buckets or any other AWS resource (queues, etc) as they are only testing the EC2 instance.

**Comment by lsh-0** [comment]
I can do that

**Comment by lsh-0** [comment]
went through and reviewed+deleted all the `pr-*` buckets, opened a PR here: https://github.com/elifesciences/builder/pull/652

**Pull request merged**
