### PR TITLE
adds collection of pdf utils 'poppler-utils'

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
huh - bit of a weird error here. Let me investigate

**Review by gnott — APPROVED** [review]
You make it look easy!

I'm not sure how the poppler-utils might be available for when testing PRs of the `elife-cleaner` library, would that need to go elsewhere too?

**Comment by lsh-0** [comment]
probably the elife-libraries formula. Looks like it already has a few deps for elife-cleaner: https://github.com/elifesciences/elife-libraries-formula/blob/master/salt/elife-libraries/init.sls#L33-L35

I'll slow the new ones in there as well.

**Comment by lsh-0** [comment]
> You make it look easy!

it kinda is ... like any tool it takes a bit of time to become familiar with it but the biggest drawback to Salt that both Giorgio and I found is that it's possible to do almost any thing with no 'blessed' way to do it.

**Pull request merged**
