### PR TITLE
removes mercurial from list of dependencies

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The `master` branch of `elife-bot` seems to still depend on it:
```
[34.230.17.83] out:           ID: elife-bot-virtualenv
[34.230.17.83] out:     Function: cmd.run
[34.230.17.83] out:         Name: ./install.sh
[34.230.17.83] out:       Result: False
[34.230.17.83] out:      Comment: Command "./install.sh" run
[34.230.17.83] out:      Started: 03:25:12.262800
[34.230.17.83] out:     Duration: 11439.384 ms
[34.230.17.83] out:      Changes:   
[34.230.17.83] out:               ----------
[34.230.17.83] out:               pid:
[34.230.17.83] out:                   914
[34.230.17.83] out:               retcode:
[34.230.17.83] out:                   1
[34.230.17.83] out:               stderr:
[34.230.17.83] out:                     Running setup.py (path:/opt/elife-bot/venv/src/jats-scraper/setup.py) egg_info for package jats-scraper produced metadata for project name unknown. Fix your #egg=jats-scraper fragments.
[34.230.17.83] out:                     Error [Errno 2] No such file or directory while executing command hg clone --noupdate -q https://bitbucket.org/lskibinski/scraper /opt/elife-bot/venv/src/scraper
[34.230.17.83] out:                   Cannot find command 'hg' - do you have 'hg' installed and in your PATH?
```
Maybe the removal has not propagated there yet?

**Comment by gnott** [comment]
If it needs an updated ``elife-bot`` ``master`` branch, it hadn't been updated yet from the recent changes sitting in the ``approved`` branch. I clicked to deploy it now so we should have an up-to-date ``master`` branch in a few moments.

**Comment by gnott** [comment]
Tests passed as a result I think!

**Comment by lsh-0** [comment]
I'm piggy backing on this branch to also remove java from the dependencies.

**Comment by lsh-0** [comment]
I'm going to close and re-open this PR

**Comment by lsh-0** [comment]
new PR here: https://github.com/elifesciences/elife-bot-formula/pull/27

**Pull request closed without merging**
