### PR TITLE
feat: ubuntu 16.04

### PR DESCRIPTION
**Pull request by lsh-0**
removed conditional code relating to an ec2 instance that doesn't exist

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Merging master into this to keep it up to date, and to check a bug in Jenkins noticing pull requests has been resolved.

**Comment by lsh-0** [comment]
thankyou

**Comment by lsh-0** [comment]
giving build a kick, the docker-ce downgrade has happened since merging master

**Comment by gnott** [comment]
I cannot tell if it is due to timeouts, Python module upgrades, or something in the formula or builder why `test-elife-bot` build is failing. There's a couple very strange errors on https://alfred.elifesciences.org/job/test-elife-bot/707 maybe worth looking at please.

**Comment by lsh-0** [comment]
this build is green, are these errors related? I'll take a look but discussion might be better off somewhere else

**Comment by gnott** [comment]
Could be unrelated to this, haha, seeing as it isn't merged yet. Sorry for the spam.

**Pull request merged**
