### PR TITLE
Some cfg file values for settings.py

### PR DESCRIPTION
**Pull request by gnott**
Matches with `elife-bot` PR https://github.com/elifesciences/elife-bot/pull/987 where `letterparser_config_file` and `letterparser_config_section` is added to the example settings file.

I noticed there were a bunch of other settings omitted from the example file in this project, and I added those to this first commit.

There are even more settings missing here, including the digest parser and digest API settings and possibly more (I didn't compare in great detail).

Do any reviewers think it is a good idea to compare all the values in `settings.py` to the https://github.com/elifesciences/elife-bot/blob/develop/settings-example.py file so these are more a one-to-one match?

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This file is just an example that is used in building Vagrant VMs but nowhere else. https://github.com/elifesciences/builder-private/blob/master/salt/elife-bot/config/opt-elife-bot-settings.py is the one we really want to get right, no opinions from me on what should be in this example, but it's a file that "should be there" to complete the build but will never run workflow or activities in practice as it lacks AWS credentials (and shouldn't have them).

**Comment by lsh-0** [comment]
I use vagrant VMs heavily when testing changes to project formulas, like upgrading instances to newer OS or adding new resources like an extra disk etc. 

Projects that don't keep their formula settings synchronised with builder-private/builder-configuration have lead to many headaches for me.

**Comment by giorgiosironi** [comment]
> Projects that don't keep their formula settings synchronised with builder-private/builder-configuration have lead to many headaches for me.

Agreed that this should be kept in sync

**Comment by gnott** [comment]
I did a comparison with the `settings.py` file we use right now, deleted and added settings as separate commits as I edited. I think this will still me merge-worthy, having little effect on real running code.

**Pull request merged**
