### PR TITLE
Feature: updated coverletter

### PR DESCRIPTION
**Pull request by lsh-0**
prepping formula for updated strip-coverletter script

merge order:
* this
* strip-coverletter: https://github.com/elifesciences/strip-coverletter/pull/2

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The steps are clear enough, we could try to use the Docker container in the future.

**Comment by giorgiosironi** [comment]
Build failed with
```
The following resource(s) failed to create: [ElifeBotFormulaPr13ElifeBotSessionsBucket, ElifeBotEventPropertyElifeBotFormulaPr13Topic, ElifeBotFormulaPr13ElifePublishedBucket, ElifeBotFormulaPr13ElifeSilentCorrectionsBucket].
```
All have parameterized name, perhaps a permission denied to Alfred?

**Comment by giorgiosironi** [comment]
Didn't have time to investigate but check if https://console.aws.amazon.com/iam/home?region=us-east-1#/users/elife-alfred needs other policies like https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::512686554592:policy/BuilderCreatorRDS that solved the problem of using RDS in formula pipelines in `crm`.

**Comment by gnott** [comment]
As long as the interface of ``/opt/strip-coverletter/strip-coverletter.sh`` in the project remains the same (looks like yes?) then the integration with the PackagePOA activity should be ok. I will defer the testing and detailed review to @giorgiosironi since you already started.

**Comment by lsh-0** [comment]
yes, the interface stays the same and only a single file is emitted upon success. the changes are to add new dependencies and remove old ones for strip-coverletter - in fact, I might shift the strip-coverletter stuff to it's own `.sls` file so it's clear

**Comment by lsh-0** [comment]
didn't get time to debug this today, I have been neck deep in bot-lax-adaptor. hopefully Fri

**Comment by lsh-0** [comment]
the s3 bucket isn't being destroyed:
```
15:46:04 UTC+1050 | CREATE_FAILED | AWS::S3::Bucket | ElifeBotFormulaPr13ElifePublishedBucket | elife-bot-formula-pr-13-elife-published already exists
```

**Comment by lsh-0** [comment]
about effing time ...

**Comment by giorgiosironi** [comment]
> I can see leftover buckets from other PRs in there as well. We might have a do-not-delete policy on them in builder. 

I know they can't be deleted if they have contents, but that should not apply here. Must be the `DeletionPolicy`.

**Comment by lsh-0** [comment]
yeah, they were empty

**Pull request merged**
